### PR TITLE
Update to Vue 2

### PR DESCRIPTION
**Pull request by KayLeung**
- Upgrade to Vue 2.x
- Upgrade dependencies

### CODE REVIEW

**Comment by Chi-teck** [comment]
Thanks. It woks, but rendering elements is very flickering.

**Comment by KayLeung** [comment]
flickering? on link clicking or filtering?

**Comment by Chi-teck** [comment]
On sorting and filtering.

**Comment by KayLeung** [comment]
Ahh I see. The table has no fixed width columns. When the data response is not fast enough, the `loading...` text affected the column width size.

**Comment by KayLeung** [comment]
@Chi-teck, the problem was fixed. I also merged a PR from @elstudio. Thanks.

**Comment by Chi-teck** [comment]
It is rather major change so I created a new 8.x-2.x branch for this. Also I added @KayLeung and @elstudio as collaborators because I am not actively using Vue at the present time. Thanks!

**Pull request merged**
